In [17]:
import numpy as np
import pandas as pd

Создание массива

In [3]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

Функция array() преобразует вложенные элементы в массив. Считается, что все хранящиеся в массивах NumPy данные должны относиться только к одному типу. Тип элементов массива соответствует типу элементов вложенной исходной последовательности, но в момент создания массива его можно изменить, задав параметр dtype требуемого типа. Для того, чтобы узнать тип данных элементов массива, используем метод dtype:

In [6]:
arr2 = np.array([5,6,7,8], dtype = float)
arr2.dtype

dtype('float64')

In [11]:
arr3 = np.array([1,2,2.2,3.3])
arr3

array([1. , 2. , 2.2, 3.3])

In [16]:
arr4 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr4.shape

(3, 3)

Массив из Pandas

В процессе анализа данных возникают ситуации, когда требуется выполнить с данными, хранящимися в Pandas DataFrame, сложные математические операции. Мы можем преобразовать датафрейм или его часть, содержащую количественные показатели, в объект ndarray с помошью функции values библиотеки Pandas:

In [18]:
df = pd.DataFrame()
x = df.values
type(x)

numpy.ndarray

In [19]:
my_series = pd.Series([5, 6, 7, 8, 9, 10])
my_series.values

array([ 5,  6,  7,  8,  9, 10], dtype=int64)

Другие способы создания массива

In [24]:
np.empty(5) # одномерный массив из пяти элементов, память для которого выделена, но не инициализирована

array([2.78134232e-309, 8.45528066e-307, 1.94906318e+289, 2.04295003e-236,
       5.40553343e+173])

In [25]:
np.zeros((10, 7)) # массив размером 10x7, заполненный нулями 

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [71]:
np.ones((3,3,3)) # массив размером 3х3х3, заполненный единицами 

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [75]:
np.eye(3) # единичная матрица (элементы главной диагонали равны 1, остальные — 0) размера 3х3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
np.full((3, 5), 3.14)  # массив 3x5 заполненный числом 3.14

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [29]:
np.arange(0, 21, 7)  # одномерный массив, заполненный числами в диапазоне от 0 до 20 с шагом 7

array([ 0,  7, 14])

In [30]:
np.linspace(0, 1, 5)  # массив из пяти чисел, равномерно распределённых в интервале между 0 и 1 включительно

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [79]:
np.random.randint(0, 10, (3, 3))  # массив размера 3х3, заполненный случайными числами из диапазона от 0 до 9 (включительно)

array([[6, 3, 7],
       [0, 1, 8],
       [3, 4, 2]])

In [62]:
my_secret = [x for x in range(1, 301, 7) if x%10 == 7 or x%10 == 1]
np.array([my_secret, [x/2 for x in my_secret], [x-100 for x in my_secret]])

array([[  1. ,  57. ,  71. , 127. , 141. , 197. , 211. , 267. , 281. ],
       [  0.5,  28.5,  35.5,  63.5,  70.5,  98.5, 105.5, 133.5, 140.5],
       [-99. , -43. , -29. ,  27. ,  41. ,  97. , 111. , 167. , 181. ]])

In [ ]:
Упражнения

Потренируемся извлекать из двумерного массива отдельные элементы и их срезы и производить над ними математические
действия. Задания блока будем выполнять на примере массива, созданного кодом:

In [157]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])

Чему равна сумма элементов последнего столбца массива? Ответ округлите до двух цифр после запятой:

In [83]:
np.sum(big_secret[:, -1])

3154.332495807108

In [100]:
sum = 0
for i in big_secret[:, -1]:
    sum += i
print(round(sum,2))

3154.33


Выделите из каждой строки массива big_secret первые 5 элементов. Чему равна сумма элементов главной диагонали получившейся матрицы? Округлите ответ до двух цифр после запятой:

In [121]:
front = big_secret[:, :5]
#print(front)
sum = 0
for i in range(len(front[0])):
    for j in range(len(front)):
        if i == j:
            sum += front[i,j]
print(round(sum, 2))

121.37


Выделите из каждой строки массива big_secret последние 5 элементов. Чему равно произведение элементов главной диагонали получившейся матрицы? Введите полученный результат без изменений и округлений.

In [128]:
rear = big_secret[:, -5:]
comp = 1
for i in range(len(rear[0])):
    for j in range(len(rear)):
        if i == j:
            comp *= rear[i,j]
print(comp)

341505315559.2347


Проверим знания! Продолжим работать с массивом big_secret. Замените на 1 все элементы, у которых оба индекса нечётные, и на -1 все элементы, у которых оба индекса чётные.

In [158]:
big_secret[::2,::2] = -1

In [159]:
big_secret[1::2,1::2] = 1

Выделите из каждой строки обновлённого массива big_secret первые 5 элементов. Чему равна сумма элементов главной диагонали получившейся матрицы? Введите полученный ответ без изменений и округлений.

In [161]:
front = big_secret[:,:5]
sum = 0
for i in range(len(front[0])):
    for j in range(len(front)):
        if i == j:
            sum += front[i,j]
print(round(sum, 2))

-1.0


Выделите из каждой строки обновлённого массива big_secret последние 5 элементов. Чему равно произведение элементов главной диагонали получившейся матрицы? Введите полученный результат без изменений и округлений.

In [162]:
rear = big_secret[:,-5:]
comp = 1
for i in range(len(rear[0])):
    for j in range(len(rear)):
        if i == j:
            comp *= rear[i,j]
print(comp)

-1.0


Операции с массивами

In [164]:
a = np.array([3,6,9])
b = np.array([12,15,18])

In [165]:
result1 = a+b
result2 = b-a
result3 = a*b
result4 = a/b
result5 = a*2
print(f'Сумма: {result1}\nРазность: {result2}\nПроизведение: {result3}\nЧастное: {result4}\nУмножение на число: {result5}')

Сумма: [15 21 27]
Разность: [9 9 9]
Произведение: [ 36  90 162]
Частное: [0.25 0.4  0.5 ]
Умножение на число: [ 6 12 18]


Для превращения массива одной размерности в массив другой — обычно для преобразования одномерного массива в многомерный — используется метод reshape. Изменить размерность массива можно только в том случае, если число элементов в исходном и в целевом массиве совпадает:

In [166]:
my_array = np.random.randint(0, 10, 20)
my_array.reshape((4,5))

array([[3, 4, 2, 8, 7],
       [1, 8, 4, 0, 4],
       [7, 9, 3, 3, 9],
       [6, 5, 3, 0, 6]])

Для преобразования многомерного массива в одномерный используется метод flatten:

In [167]:
my_array = np.array([[1,2,3], [11,22,33], [111,222,333]])
my_array.flatten()

array([  1,   2,   3,  11,  22,  33, 111, 222, 333])

Научимся сравнивать элементы массива с числом и извлекать из него только те элементы, которые больше или меньше заданного числа. Для этого создадим массив размера 3х4, произвольно заполненный числами от 0 до 10. При создании массива используется генератор случайных чисел, так что у вас могут получиться другие значения:

In [174]:
my_array = np.random.randint(0, 10, (3,4))
my_array

array([[7, 3, 9, 7],
       [8, 1, 3, 2],
       [8, 3, 5, 9]])

In [175]:
my_array<5

array([[False,  True, False, False],
       [False,  True,  True,  True],
       [False,  True, False, False]])

In [176]:
my_array[my_array<5]

array([3, 1, 3, 2, 3])

Маска нужна для выбора только определенных строк или столбцов из всего массива и скрытия остальных. Маска в Python задаётся при помощи булевых 0 и 1, где 0 скрывает столбец или строку, а 1 оставляет ее на виду. Выведем первый и третий столбец массива:

In [177]:
mask = np.array([1, 0, 1, 0], dtype=bool)
my_array[:, mask]

array([[7, 9],
       [8, 3],
       [8, 5]])

Сортировка двумерных массивов

In [179]:
my_array = np.random.randint(0, 10, (4, 6))
my_array

array([[0, 1, 3, 8, 8, 5],
       [3, 6, 7, 4, 1, 1],
       [6, 5, 1, 0, 2, 6],
       [4, 5, 4, 2, 4, 7]])

In [180]:
np.sort(my_array, axis=1)

array([[0, 1, 3, 5, 8, 8],
       [1, 1, 3, 4, 6, 7],
       [0, 1, 2, 5, 6, 6],
       [2, 4, 4, 4, 5, 7]])

In [181]:
np.sort(my_array, axis=0)

array([[0, 1, 1, 0, 1, 1],
       [3, 5, 3, 2, 2, 5],
       [4, 5, 4, 4, 4, 6],
       [6, 6, 7, 8, 8, 7]])

In [182]:
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]

great_secret = np.array([first, second, third]).T

Сколько столбцов содержит массив great_secret?

In [184]:
3

3

Чему равна сумма косинусов элементов первой строки массива great_secret? Ответ округлите до двух знаков после запятой.

In [192]:
first = great_secret[0, :]
np.sum(np.cos(first))

0.16006721889793019

Чему равна сумма элементов массива great_secret, значение которых больше 50?

In [193]:
np.sum(great_secret[great_secret > 50])

5470.0

Переведите массив great_secret в одномерную форму. Какое значение в получившемся массиве имеет элемент с индексом 150? Скопируйте ответ из Jupyter Notebook без изменений.

In [195]:
great_secret.flatten()[150]

7.0710678118654755

Отсортируйте значения столбцов массива great_secret по возрастанию. Чему равна сумма элементов последней строки отсортированного массива? Ответ округлите до двух цифр после запятой.

In [199]:
np.sum(np.sort(great_secret, axis=0)[-1,:])

115.12148016521353

Математические и статистические операции

In [204]:
students = np.array([[1,135,34,4],
                   [2,160,43,5],
                   [3,163,40,4.3],
                   [4,147,44,5],
                   [5,138,41,4.7],
                   [6,149,54,3.9],
                   [7,136,39,4.2],
                   [8,154,48,4.9],
                   [9,137,35,3.7],
                   [10,165,60,4.6]])

In [205]:
mean = np.mean(students[:,-1])
mean

4.430000000000001

In [206]:
median = np.median(students[:,-1])
median

4.449999999999999

In [207]:
sort = np.sort(students[:,-1])
(sort[4]+sort[5])/2

4.449999999999999

Чему равно медианное значение массы тела школьников?

In [208]:
mass = np.median(students[:,-2])
mass

42.0

На сколько среднее арифметическое массы тела школьников больше медианного значения для этого же показателя? Дайте ответ в килограммах с точностью до одной десятой кг.

In [214]:
difference = np.mean(students[:,-2]) - np.median(students[:,-2])
difference

1.7999999999999972

Коэффициент корреляции

In [215]:
corr = np.corrcoef(students[:,1], students[:,2])
corr

array([[1.        , 0.64314431],
       [0.64314431, 1.        ]])

Между какой парой признаков в массиве students наблюдается минимальная корреляция, из предложенных вариантов?

In [217]:
corr1 = np.corrcoef(students[:,1], students[:,-1])
corr1

array([[1.        , 0.46293714],
       [0.46293714, 1.        ]])

In [218]:
corr2 = np.corrcoef(students[:,-2], students[:,-1])
corr2

array([[1.        , 0.29801325],
       [0.29801325, 1.        ]])

In [ ]:
Стандартное отклонение

In [219]:
std = np.std(students[:,1])
std

11.083320801997928

Используя имеющийся набор данных о школьниках, найдите, чему равно стандартное отклонение их средних баллов.

In [220]:
std = np.std(students[:,-1])
std

0.4517742799230607

Посчитайте, чему равна дисперсия значений веса школьников.

Эту величину можно получить двумя способами: математически - используя определение дисперсии и известную функцию в блоке, или самостоятельно - используя подходящую функцию модуля NumPy.

In [222]:
disp = np.std(students[:,-2])**2
disp

60.36

In [235]:
my_array = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]])

Создайте массив my_sin, состоящий из синусов элементов массива my_array. Посчитайте, чему равна сумма элементов полученного массива. Ответ округлите до трёх цифр после запятой.

In [265]:
my_sin = np.sin(my_array)
round(np.sum(my_sin), 3)

-0.058

Замените элементы в центральном фрагменте 3 х 3 массива my_sin на единицы.Чему равна сумма элементов изменённого массива? Ответ округлите до трёх знаков после запятой.

In [267]:
my_sin[1:4,1:4] = 1
round(np.sum(my_sin), 3)

7.572

Преобразуйте первые четыре столбца массива my_sin в массив из 10 строк и 2 столбцов. Чему равна сумма элементов первого столбца получившегося массива? Ответ округлите до трёх заков после точки-разделителя. Используйте преобразованный в предыдущем задании массив my_sin.

In [269]:
my_shape = my_sin[:,:4].reshape((10,2))
print(my_sin,'\n')
print(my_shape)
round(np.sum(my_shape[:,0]), 3)

[[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
 [-0.2794155   1.          1.          1.         -0.54402111]
 [-0.99999021  1.          1.          1.          0.65028784]
 [-0.28790332  1.          1.          1.          0.91294525]
 [ 0.83665564 -0.00885131 -0.8462204  -0.90557836 -0.13235175]] 

[[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]
 [-0.2794155   1.        ]
 [ 1.          1.        ]
 [-0.99999021  1.        ]
 [ 1.          1.        ]
 [-0.28790332  1.        ]
 [ 1.          1.        ]
 [ 0.83665564 -0.00885131]
 [-0.8462204  -0.90557836]]


2.406

Создайте массив bigdata, содержащий квадраты всех нечётных чисел в диапазоне от 100 до 1000.

In [273]:
bigdata = np.array([x**2 for x in range(100, 1000) if x%2])

Чему равна медиана массива bigdata?

In [274]:
np.median(bigdata)

302501.0

Чему равно стандартное отклонение для массива bigdata? Ответ округлите до целых:

In [276]:
round(np.std(bigdata), 0)

292095.0

Чему равен коэффициент корреляции между элементами массива bigdata с чётными и нечётными индексами? Введите полученный ответ без изменений и округлений.

In [278]:
corel = np.corrcoef(bigdata[::2], bigdata[1::2])
corel

array([[1.        , 0.99999973],
       [0.99999973, 1.        ]])

Напечатать версию и конфигурацию

In [279]:
print(np.__version__)
np.show_config()

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Sinigr/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Sinigr/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Sinigr/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Sinigr/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Sinigr/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Sinigr/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Sinigr/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Sinigr/anaconda3\\Library\\include']


Создать вектор (одномерный массив) размера 10, заполненный нулями

In [280]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Создать вектор размера 10, заполненный единицами

In [281]:
Z = np.ones(10)
print(Z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Создать вектор размера 10, заполненный числом 2.5

In [282]:
Z = np.full(10, 2.5)
print(Z)

[2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5]


Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [284]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Создать вектор со значениями от 10 до 49

In [285]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Развернуть вектор (первый становится последним)

In [287]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [288]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [289]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


Создать 3x3 единичную матрицу

In [290]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Создать массив 3x3x3 со случайными значениями

In [291]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.3191424  0.24248479 0.98183934]
  [0.94865392 0.87566925 0.37529951]
  [0.43660848 0.61573321 0.88511261]]

 [[0.34136338 0.54090273 0.65895448]
  [0.81574589 0.3780261  0.51936889]
  [0.012514   0.67578662 0.75888116]]

 [[0.90678455 0.32553094 0.43742066]
  [0.06738391 0.05491762 0.4470677 ]
  [0.04420567 0.68856122 0.16465848]]]


Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [295]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.0015624493575386866 0.9969817709808741


Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [345]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.5072859171401526


Создать матрицу с 0 внутри, и 1 на границах

In [347]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Выяснить результат следующих выражений

In [358]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


Создать 5x5 матрицу с 1,2,3,4 под диагональю

In [363]:
Z = np.diag(np.arange(1, 5), k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


Создать 8x8 матрицу и заполнить её в шахматном порядке

In [364]:
Z = np.zeros((8,8), dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [365]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [366]:
Z = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Перемножить матрицы 5x3 и 3x2

In [367]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [368]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


Создать 5x5 матрицу со значениями в строках от 0 до 4

In [369]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


Есть генератор, сделать с его помощью массив

In [371]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [374]:
Z = np.linspace(0,1,12)[1:-1]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


Отсортировать вектор

In [378]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.19701812 0.425444   0.44342698 0.4871318  0.53258821 0.73328216
 0.77268603 0.95676073 0.97169066 0.99987117]


Проверить, одинаковы ли 2 numpy массива

In [524]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

True


Сделать массив неизменяемым

In [527]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

Дан массив 10x2 (точки в декартовой системе координат), преобразовать в полярную

In [535]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.hypot(X, Y)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.59137822 0.43035837 0.81567195 0.76803885 0.28978425 1.06595645
 1.13000576 0.17649459 0.22753897 0.24663337]
[1.13612515 0.61638771 0.69546856 1.41444462 0.4491548  0.90395397
 0.73150715 1.28162993 1.26443452 0.02964442]
